//
//  EZMovieDetailInterfaces.swift
//  EZCinema
//
//  Created by Edu on 17/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol EZMovieDetailWireframeInterface: WireframeInterface {
}

protocol EZMovieDetailViewInterface: ViewInterface {
    func onSetMovieDetail(movieIn: Movie?)
}

protocol EZMovieDetailPresenterInterface: PresenterInterface {
    func onGetMovieDetail()
}

protocol EZMovieDetailInteractorInterface: InteractorInterface {
    func getGenreList(completion: @escaping (Result<ResponseGenreList, RequestError>) -> Void)
}
