//
//  EZMovieDetailWireframe.swift
//  EZCinema
//
//  Created by Edu on 17/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EZMovieDetailWireframe: BaseWireframe {

    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "EZMovieDetail", bundle: nil)

    // MARK: - Module setup
    init(movieIn: Movie?) {
        let moduleViewController = storyboard.instantiateViewController(ofType: EZMovieDetailViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = EZMovieDetailInteractor()
        let presenter = EZMovieDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, movieIn: movieIn)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions
extension EZMovieDetailWireframe: EZMovieDetailWireframeInterface {
}
