//
//  EZMovieDetailInteractor.swift
//  EZCinema
//
//  Created by Edu on 17/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EZMovieDetailInteractor {
    private var mService = MainService()
}

// MARK: - Extensions 
extension EZMovieDetailInteractor: EZMovieDetailInteractorInterface {
    func getGenreList(completion: @escaping (Result<ResponseGenreList, RequestError>) -> Void) {
        self.mService.getGenreList(completion: completion)
    }
}
