//
//  EZMovieListWireframe.swift
//  EZCinema
//
//  Created by Edu on 17/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EZMovieListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "EZMovieList", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: EZMovieListViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = EZMovieListInteractor()
        let presenter = EZMovieListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension EZMovieListWireframe: EZMovieListWireframeInterface {
    
    func pushToMovieDetail(movieIn: Movie?) {
        let mDWireframe = EZMovieDetailWireframe(movieIn: movieIn)
        self.navigationController?.pushWireframe(mDWireframe)
    }
}
