//
//  EZMovieListInterfaces.swift
//  EZCinema
//
//  Created by Edu on 17/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol EZMovieListWireframeInterface: WireframeInterface {
    func pushToMovieDetail(movieIn: Movie?)
}

protocol EZMovieListViewInterface: ViewInterface {
    func onSetMovieList(movieListIn: [Movie]?)
    func onSetUpcomingList(movieListIn: [Movie]?)
}

protocol EZMovieListPresenterInterface: PresenterInterface {
    func onGetMovieList()
    func onGetUpcomingList()
    func onMovieSelected(movieIn: Movie?)
}

protocol EZMovieListInteractorInterface: InteractorInterface {
    func getMovieList(completion: @escaping (Result<ResponseMovieList, RequestError>) -> Void)
    func getUpcomingList(completion: @escaping (Result<ResponseMovieList, RequestError>) -> Void)
}
