//
//  EZMovieListInteractor.swift
//  EZCinema
//
//  Created by Edu on 17/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EZMovieListInteractor {
    
    private let mService = MainService()
}

// MARK: - Extensions 
extension EZMovieListInteractor: EZMovieListInteractorInterface {
    
    func getMovieList(completion: @escaping (Result<ResponseMovieList, RequestError>) -> Void) {
        self.mService.getMovieList(completion: completion)
    }
    
    func getUpcomingList(completion: @escaping (Result<ResponseMovieList, RequestError>) -> Void) {
        self.mService.getUpcomingList(completion: completion)
    }
}
